In [1]:
#python 操作mysql
#增删改查。

In [6]:
import pymysql

In [3]:
mysql_conn = pymysql.connect(host= '127.0.0.1', port= 3306, user= 'root', password= ' ', db= 'whgtest')

In [4]:
mysql_conn

In [6]:
text = "let's go"
text = mysql_conn.escape(text)
sql = "INSERT INTO test_mysql (name, num, text) VALUES ('{0}','{1}', {2})".format('Zarten_1', 1, text)
try:
    with mysql_conn.cursor() as cursor:
        cursor.execute(sql)
    mysql_conn.commit()
except Exception as e:
    mysql_conn.rollback()
mysql_conn.close()

In [13]:
#批量执行sql文件，非查询语句。
# %%time
mysql_conn = pymysql.connect(host= '127.0.0.1', port= 3306, user= 'root', password= '  ', db= 'whgtest')
with open("./sql/test.sql",encoding="utf-8") as f:
    full_sql=f.read();
    sql_commands=full_sql.split(';')[:-1]
#     print(full_sql)
for sql_command in sql_commands:
    try:
        mysql_conn.cursor().execute(sql_command)
        mysql_conn.commit()
    except Exception as e:
        mysql_conn.rollback()
        print(e)
mysql_conn.cursor().close()
mysql_conn.close()

In [ ]:
#批量执行sql文件，查询语句

In [ ]:
#excel表导入数据库（每10000条写入到数据库一次）

In [53]:
import pymysql
import xlrd
import sysimport pymysql
import xlrd
import sys
'''
    连接数据库
    args：db_name（数据库名称）
    returns:db
'''
 
 
def mysql_link(db_name):
    try:
        db = pymysql.connect(host="127.0.0.1", user="root",
                             passwd="",
                             db=db_name,
                             charset='utf8')
        return db
    except:
        print("could not connect to mysql server")
        
'''
    读取excel函数
    args：excel_file（excel文件，目录在py文件同目录）
    returns：book
'''
 
 
def open_excel(excel_file):
    try:
        book = xlrd.open_workbook(excel_file)  # 文件名，把文件与py文件放在同一目录下
        print(sys.getsizeof(book))
        return book
    except:
        print("open excel file failed!")
 
 
'''
    执行插入操作
    args:db_name（数据库名称）
         table_name(表名称）
         excel_file（excel文件名，把文件与py文件放在同一目录下）
 
'''
 
 
def store_to(db_name, table_name, excel_file):
    db = mysql_link(db_name)  # 打开数据库连接
    cursor = db.cursor()  # 使用 cursor() 方法创建一个游标对象 cursor
 
    book = open_excel(excel_file)  # 打开excel文件
    sheets = book.sheet_names()  # 获取所有sheet表名
    for sheet in sheets:
        sh = book.sheet_by_name(sheet)  # 打开每一张表
        row_num = sh.nrows
        print(row_num)
        list = []  # 定义列表用来存放数据
        num = 0  # 用来控制每次插入的数量
        for i in range(1, row_num):  # 第一行是标题名，对应表中的字段名所以应该从第二行开始，计算机以0开始计数，所以值是1
            row_data = sh.row_values(i)  # 按行获取excel的值
            value = (row_data[0], row_data[1], row_data[2])
            list.append(value)  # 将数据暂存在列表
            print(list)
            num += 1
            if( num>= 10000 ):  # 每一万条数据执行一次插入
                print(sys.getsizeof(list))
                sql = "INSERT INTO " + table_name + " (name, num, text)\
                VALUES(%s,%s,%s)"
#                 print(sql)
                cursor.executemany(sql, list)  # 执行sql语句
 
                num = 0  # 计数归零
                list.clear()  # 清空list
                print("worksheets: " + sheet + " has been inserted 10000 datas!")
            else:
                print(sys.getsizeof(list))
                sql = "INSERT INTO " + table_name + " (name, num, text)\
                VALUES(%s,%s,%s)"
#                 print(sql)
                cursor.executemany(sql, list)  # 执行sql语句
#                 print("worksheets: " + sheet + " has been inserted"+ str(num) +"datas!")
                num = 0  # 计数归零
                list.clear()  # 清空list
                
    print("worksheets: " + sheet + " has been inserted " + str(row_num) + " datas!")
    db.commit()  # 提交
    cursor.close()  # 关闭连接
    db.close()
 
if __name__ == '__main__':
    store_to('whgtest', 'test_mysql2', 'test.xlsx')
'''
    连接数据库
    args：db_name（数据库名称）
    returns:db
'''
 
 
def mysql_link(db_name):
    try:
        db = pymysql.connect(host="127.0.0.1", user="root",
                             passwd="",
                             db=db_name,
                             charset='utf8')
        return db
    except:
        print("could not connect to mysql server")
        
'''
    读取excel函数
    args：excel_file（excel文件，目录在py文件同目录）
    returns：book
'''
 
 
def open_excel(excel_file):
    try:
        book = xlrd.open_workbook(excel_file)  # 文件名，把文件与py文件放在同一目录下
        print(sys.getsizeof(book))
        return book
    except:
        print("open excel file failed!")
 
 
'''
    执行插入操作
    args:db_name（数据库名称）
         table_name(表名称）
         excel_file（excel文件名，把文件与py文件放在同一目录下）
 
'''
 
 
def store_to(db_name, table_name, excel_file):
    db = mysql_link(db_name)  # 打开数据库连接
    cursor = db.cursor()  # 使用 cursor() 方法创建一个游标对象 cursor
 
    book = open_excel(excel_file)  # 打开excel文件
    sheets = book.sheet_names()  # 获取所有sheet表名
    for sheet in sheets:
        sh = book.sheet_by_name(sheet)  # 打开每一张表
        row_num = sh.nrows
        print(row_num)
        list = []  # 定义列表用来存放数据
        num = 0  # 用来控制每次插入的数量
        for i in range(1, row_num):  # 第一行是标题名，对应表中的字段名所以应该从第二行开始，计算机以0开始计数，所以值是1
            row_data = sh.row_values(i)  # 按行获取excel的值
            value = (row_data[0], row_data[1], row_data[2])
            list.append(value)  # 将数据暂存在列表
            print(list)
            num += 1
            if( num>= 10000 ):  # 每一万条数据执行一次插入
                print(sys.getsizeof(list))
                sql = "INSERT INTO " + table_name + " (name, num, text)\
                VALUES(%s,%s,%s)"
#                 print(sql)
                cursor.executemany(sql, list)  # 执行sql语句
 
                num = 0  # 计数归零
                list.clear()  # 清空list
                print("worksheets: " + sheet + " has been inserted 10000 datas!")
            else:
                print(sys.getsizeof(list))
                sql = "INSERT INTO " + table_name + " (name, num, text)\
                VALUES(%s,%s,%s)"
#                 print(sql)
                cursor.executemany(sql, list)  # 执行sql语句
#                 print("worksheets: " + sheet + " has been inserted"+ str(num) +"datas!")
                num = 0  # 计数归零
                list.clear()  # 清空list
                
    print("worksheets: " + sheet + " has been inserted " + str(row_num) + " datas!")
    db.commit()  # 提交
    cursor.close()  # 关闭连接
    db.close()
 
if __name__ == '__main__':
    store_to('whgtest', 'test_mysql2', 'test.xlsx')

64
118
[('wrewr', 1.0, 'dfdsgd')]
104
[('werw', 2.0, 'dfgdfgdfg')]
104
[('dffgdfg', 3.0, 'dfg')]
104
[('wrewr', 4.0, 'dfdsgd')]
104
[('werw', 5.0, 'dfgdfgdfg')]
104
[('dffgdfg', 6.0, 'dfg')]
104
[('wrewr', 7.0, 'dfdsgd')]
104
[('werw', 8.0, 'dfgdfgdfg')]
104
[('dffgdfg', 9.0, 'dfg')]
104
[('wrewr', 10.0, 'dfdsgd')]
104
[('werw', 11.0, 'dfgdfgdfg')]
104
[('dffgdfg', 12.0, 'dfg')]
104
[('wrewr', 13.0, 'dfdsgd')]
104
[('werw', 14.0, 'dfgdfgdfg')]
104
[('dffgdfg', 15.0, 'dfg')]
104
[('wrewr', 16.0, 'dfdsgd')]
104
[('werw', 17.0, 'dfgdfgdfg')]
104
[('dffgdfg', 18.0, 'dfg')]
104
[('wrewr', 19.0, 'dfdsgd')]
104
[('werw', 20.0, 'dfgdfgdfg')]
104
[('dffgdfg', 21.0, 'dfg')]
104
[('wrewr', 22.0, 'dfdsgd')]
104
[('werw', 23.0, 'dfgdfgdfg')]
104
[('dffgdfg', 24.0, 'dfg')]
104
[('wrewr', 25.0, 'dfdsgd')]
104
[('werw', 26.0, 'dfgdfgdfg')]
104
[('dffgdfg', 27.0, 'dfg')]
104
[('wrewr', 28.0, 'dfdsgd')]
104
[('werw', 29.0, 'dfgdfgdfg')]
104
[('dffgdfg', 30.0, 'dfg')]
104
[('wrewr', 31.0, 'dfdsgd')]
104
[('werw', 32.0, 'dfgdfgdfg')]
104
[('dffgdfg', 33.0, 'dfg')]
104
[('wrewr', 34.0, 'dfdsgd')]
104
[('werw', 35.0, 'dfgdfgdfg')]
104
[('dffgdfg', 36.0, 'dfg')]
104
[('wrewr', 37.0, 'dfdsgd')]
104
[('werw', 38.0, 'dfgdfgdfg')]
104
[('dffgdfg', 39.0, 'dfg')]
104
[('wrewr', 40.0, 'dfdsgd')]
104
[('werw', 41.0, 'dfgdfgdfg')]
104
[('dffgdfg', 42.0, 'dfg')]
104
[('wrewr', 43.0, 'dfdsgd')]
104
[('werw', 44.0, 'dfgdfgdfg')]
104
[('dffgdfg', 45.0, 'dfg')]
104
[('wrewr', 46.0, 'dfdsgd')]
104
[('werw', 47.0, 'dfgdfgdfg')]
104
[('dffgdfg', 48.0, 'dfg')]
104
[('wrewr', 49.0, 'dfdsgd')]
104
[('werw', 50.0, 'dfgdfgdfg')]
104
[('dffgdfg', 51.0, 'dfg')]
104
[('wrewr', 52.0, 'dfdsgd')]
104
[('werw', 53.0, 'dfgdfgdfg')]
104
[('dffgdfg', 54.0, 'dfg')]
104
[('wrewr', 55.0, 'dfdsgd')]
104
[('werw', 56.0, 'dfgdfgdfg')]
104
[('dffgdfg', 57.0, 'dfg')]
104
[('wrewr', 58.0, 'dfdsgd')]
104
[('werw', 59.0, 'dfgdfgdfg')]
104
[('dffgdfg', 60.0, 'dfg')]
104
[('wrewr', 61.0, 'dfdsgd')]
104
[('werw', 62.0, 'dfgdfgdfg')]
104
[('dffgdfg', 63.0, 'dfg')]
104
[('wrewr', 64.0, 'dfdsgd')]
104
[('werw', 65.0, 'dfgdfgdfg')]
104
[('dffgdfg', 66.0, 'dfg')]
104
[('wrewr', 67.0, 'dfdsgd')]
104
[('werw', 68.0, 'dfgdfgdfg')]
104
[('dffgdfg', 69.0, 'dfg')]
104
[('wrewr', 70.0, 'dfdsgd')]
104
[('werw', 71.0, 'dfgdfgdfg')]
104
[('dffgdfg', 72.0, 'dfg')]
104
[('wrewr', 73.0, 'dfdsgd')]
104
[('werw', 74.0, 'dfgdfgdfg')]
104
[('dffgdfg', 75.0, 'dfg')]
104
[('wrewr', 76.0, 'dfdsgd')]
104
[('werw', 77.0, 'dfgdfgdfg')]
104
[('dffgdfg', 78.0, 'dfg')]
104
[('wrewr', 79.0, 'dfdsgd')]
104
[('werw', 80.0, 'dfgdfgdfg')]
104
[('dffgdfg', 81.0, 'dfg')]
104
[('wrewr', 82.0, 'dfdsgd')]
104
[('werw', 83.0, 'dfgdfgdfg')]
104
[('dffgdfg', 84.0, 'dfg')]
104
[('wrewr', 85.0, 'dfdsgd')]
104
[('werw', 86.0, 'dfgdfgdfg')]
104
[('dffgdfg', 87.0, 'dfg')]
104
[('wrewr', 88.0, 'dfdsgd')]
104
[('werw', 89.0, 'dfgdfgdfg')]
104
[('dffgdfg', 90.0, 'dfg')]
104
[('wrewr', 91.0, 'dfdsgd')]
104
[('werw', 92.0, 'dfgdfgdfg')]
104
[('dffgdfg', 93.0, 'dfg')]
104
[('wrewr', 94.0, 'dfdsgd')]
104
[('werw', 95.0, 'dfgdfgdfg')]
104
[('dffgdfg', 96.0, 'dfg')]
104
[('wrewr', 97.0, 'dfdsgd')]
104
[('werw', 98.0, 'dfgdfgdfg')]
104
[('dffgdfg', 99.0, 'dfg')]
104
[('wrewr', 100.0, 'dfdsgd')]
104
[('werw', 101.0, 'dfgdfgdfg')]
104
[('dffgdfg', 102.0, 'dfg')]
104
[('wrewr', 103.0, 'dfdsgd')]
104
[('werw', 104.0, 'dfgdfgdfg')]
104
[('dffgdfg', 105.0, 'dfg')]
104
[('wrewr', 106.0, 'dfdsgd')]
104
[('werw', 107.0, 'dfgdfgdfg')]
104
[('dffgdfg', 108.0, 'dfg')]
104
[('wrewr', 109.0, 'dfdsgd')]
104
[('werw', 110.0, 'dfgdfgdfg')]
104
[('dffgdfg', 111.0, 'dfg')]
104
[('wrewr', 112.0, 'dfdsgd')]
104
[('werw', 113.0, 'dfgdfgdfg')]
104
[('dffgdfg', 114.0, 'dfg')]
104
[('wrewr', 115.0, 'dfdsgd')]
104
[('werw', 116.0, 'dfgdfgdfg223')]
104
[('dffgdfg', 117.0, 'dfg你好')]
104
worksheets: Sheet1 has been inserted 118 datas!

In [ ]:
#一键导出表到excel表，如果超过104万多后，是否就直接导出成csv格式或txt格式。或者在另外的sheet存储。

In [54]:
# coding:utf8
import sys
import imp
imp.reload(sys)
# sys.setdefaultencoding('utf8')
#    __author__ = '郭 璞'
#    __date__ = '2016/8/20'
#    __Desc__ = 从数据库中导出数据到excel数据表中

import xlwt
# import MySQLdb
import pymysql

def export(host,user,password,dbname,table_name,outputpath):
#     conn = MySQLdb.connect(host,user,password,dbname,charset='utf8')
    conn = pymysql.connect(host="127.0.0.1", user=user,
                             passwd=password,
                             db=dbname,
                             charset='utf8')
    cursor = conn.cursor()
    count = cursor.execute('select * from '+table_name)
    print(count)
 # 重置游标的位置
    cursor.scroll(0,mode='absolute')
 # 搜取所有结果
    results = cursor.fetchall()

 # 获取MYSQL里面的数据字段名称
    fields = cursor.description
    workbook = xlwt.Workbook()
    sheet = workbook.add_sheet('table_'+table_name,cell_overwrite_ok=True)
 # 写上字段信息
    for field in range(0,len(fields)):
        sheet.write(0,field,fields[field][0])

 # 获取并写入数据段信息
        row = 1
        col = 0
    for row in range(1,len(results)+1):
        for col in range(0,len(fields)):
            sheet.write(row,col,u'%s'%results[row-1][col])

            workbook.save(outputpath)


# 结果测试
if __name__ == "__main__":
    export('localhost','root','','whgtest','test_mysql2',r'test_mysql2.xlsx')

117

In [ ]:
# %sql mysql+pymysql://ffzs:666666@localhost/test

In [3]:
%load_ext sql

In [4]:
%sql mysql+pymysql://root:whgdev@localhost/whgtest

In [5]:
%%sql
select * from
test_mysql

 * mysql+pymysql://root:***@localhost/whgtest
119 rows affected.

[('Zarten_1', 1, "let's go"),
 ('Zarten_1', 1, "let's go"),
 ('wrewr', 1, 'dfdsgd'),
 ('werw', 2, 'dfgdfgdfg'),
 ('dffgdfg', 3, 'dfg'),
 ('wrewr', 4, 'dfdsgd'),
 ('werw', 5, 'dfgdfgdfg'),
 ('dffgdfg', 6, 'dfg'),
 ('wrewr', 7, 'dfdsgd'),
 ('werw', 8, 'dfgdfgdfg'),
 ('dffgdfg', 9, 'dfg'),
 ('wrewr', 10, 'dfdsgd'),
 ('werw', 11, 'dfgdfgdfg'),
 ('dffgdfg', 12, 'dfg'),
 ('wrewr', 13, 'dfdsgd'),
 ('werw', 14, 'dfgdfgdfg'),
 ('dffgdfg', 15, 'dfg'),
 ('wrewr', 16, 'dfdsgd'),
 ('werw', 17, 'dfgdfgdfg'),
 ('dffgdfg', 18, 'dfg'),
 ('wrewr', 19, 'dfdsgd'),
 ('werw', 20, 'dfgdfgdfg'),
 ('dffgdfg', 21, 'dfg'),
 ('wrewr', 22, 'dfdsgd'),
 ('werw', 23, 'dfgdfgdfg'),
 ('dffgdfg', 24, 'dfg'),
 ('wrewr', 25, 'dfdsgd'),
 ('werw', 26, 'dfgdfgdfg'),
 ('dffgdfg', 27, 'dfg'),
 ('wrewr', 28, 'dfdsgd'),
 ('werw', 29, 'dfgdfgdfg'),
 ('dffgdfg', 30, 'dfg'),
 ('wrewr', 31, 'dfdsgd'),
 ('werw', 32, 'dfgdfgdfg'),
 ('dffgdfg', 33, 'dfg'),
 ('wrewr', 34, 'dfdsgd'),
 ('werw', 35, 'dfgdfgdfg'),
 ('dffgdfg', 36, 'dfg'),
 ('wrewr', 37, 'dfdsgd'),
 ('werw', 38, 'dfgdfgdfg'),
 ('dffgdfg', 39, 'dfg'),
 ('wrewr', 40, 'dfdsgd'),
 ('werw', 41, 'dfgdfgdfg'),
 ('dffgdfg', 42, 'dfg'),
 ('wrewr', 43, 'dfdsgd'),
 ('werw', 44, 'dfgdfgdfg'),
 ('dffgdfg', 45, 'dfg'),
 ('wrewr', 46, 'dfdsgd'),
 ('werw', 47, 'dfgdfgdfg'),
 ('dffgdfg', 48, 'dfg'),
 ('wrewr', 49, 'dfdsgd'),
 ('werw', 50, 'dfgdfgdfg'),
 ('dffgdfg', 51, 'dfg'),
 ('wrewr', 52, 'dfdsgd'),
 ('werw', 53, 'dfgdfgdfg'),
 ('dffgdfg', 54, 'dfg'),
 ('wrewr', 55, 'dfdsgd'),
 ('werw', 56, 'dfgdfgdfg'),
 ('dffgdfg', 57, 'dfg'),
 ('wrewr', 58, 'dfdsgd'),
 ('werw', 59, 'dfgdfgdfg'),
 ('dffgdfg', 60, 'dfg'),
 ('wrewr', 61, 'dfdsgd'),
 ('werw', 62, 'dfgdfgdfg'),
 ('dffgdfg', 63, 'dfg'),
 ('wrewr', 64, 'dfdsgd'),
 ('werw', 65, 'dfgdfgdfg'),
 ('dffgdfg', 66, 'dfg'),
 ('wrewr', 67, 'dfdsgd'),
 ('werw', 68, 'dfgdfgdfg'),
 ('dffgdfg', 69, 'dfg'),
 ('wrewr', 70, 'dfdsgd'),
 ('werw', 71, 'dfgdfgdfg'),
 ('dffgdfg', 72, 'dfg'),
 ('wrewr', 73, 'dfdsgd'),
 ('werw', 74, 'dfgdfgdfg'),
 ('dffgdfg', 75, 'dfg'),
 ('wrewr', 76, 'dfdsgd'),
 ('werw', 77, 'dfgdfgdfg'),
 ('dffgdfg', 78, 'dfg'),
 ('wrewr', 79, 'dfdsgd'),
 ('werw', 80, 'dfgdfgdfg'),
 ('dffgdfg', 81, 'dfg'),
 ('wrewr', 82, 'dfdsgd'),
 ('werw', 83, 'dfgdfgdfg'),
 ('dffgdfg', 84, 'dfg'),
 ('wrewr', 85, 'dfdsgd'),
 ('werw', 86, 'dfgdfgdfg'),
 ('dffgdfg', 87, 'dfg'),
 ('wrewr', 88, 'dfdsgd'),
 ('werw', 89, 'dfgdfgdfg'),
 ('dffgdfg', 90, 'dfg'),
 ('wrewr', 91, 'dfdsgd'),
 ('werw', 92, 'dfgdfgdfg'),
 ('dffgdfg', 93, 'dfg'),
 ('wrewr', 94, 'dfdsgd'),
 ('werw', 95, 'dfgdfgdfg'),
 ('dffgdfg', 96, 'dfg'),
 ('wrewr', 97, 'dfdsgd'),
 ('werw', 98, 'dfgdfgdfg'),
 ('dffgdfg', 99, 'dfg'),
 ('wrewr', 100, 'dfdsgd'),
 ('werw', 101, 'dfgdfgdfg'),
 ('dffgdfg', 102, 'dfg'),
 ('wrewr', 103, 'dfdsgd'),
 ('werw', 104, 'dfgdfgdfg'),
 ('dffgdfg', 105, 'dfg'),
 ('wrewr', 106, 'dfdsgd'),
 ('werw', 107, 'dfgdfgdfg'),
 ('dffgdfg', 108, 'dfg'),
 ('wrewr', 109, 'dfdsgd'),
 ('werw', 110, 'dfgdfgdfg'),
 ('dffgdfg', 111, 'dfg'),
 ('wrewr', 112, 'dfdsgd'),
 ('werw', 113, 'dfgdfgdfg'),
 ('dffgdfg', 114, 'dfg'),
 ('wrewr', 115, 'dfdsgd'),
 ('werw', 116, 'dfgdfgdfg'),
 ('dffgdfg', 117, 'dfg')]

In [17]:
%sql select * from test_mysql

 * mysql+pymysql://root:***@localhost/whgtest
2 rows affected.

[('Zarten_1', 1, "let's go"), ('Zarten_1', 1, "let's go")]

In [19]:
%%sql
show databases;
show tables;

 * mysql+pymysql://root:***@localhost/whgtest
5 rows affected.
1 rows affected.

[('test_mysql',)]

In [20]:
%%sql
show databases;

 * mysql+pymysql://root:***@localhost/whgtest
5 rows affected.

[('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sys',),
 ('whgtest',)]